version: '2'

services:
  app:
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "42040:8000"
    command:  bash -c "sleep 10; python manage.py migrate --noinput; python manage.py runserver 0.0.0.0:8000"
